# Arc Mainnet (chain 5042). Copy to .env and replace placeholders.
# Arc uses USDC for both settlement and gas. The ERC-20 interface below uses
# 6 decimals; native RPC gas accounting uses 18 decimals.
PRIVATE_KEY=your_private_key_here
RPC_URL=
RPC_URLS=https://rpc.mainnet.arc.io,https://rpc.drpc.mainnet.arc.io,https://rpc.quicknode.mainnet.arc.io
CHAIN_ID=5042

TOKEN_ADDRESS=0x...your_arc_token_address_here...
TOKEN_SYMBOL=YOUR_TOKEN
WETH_ADDRESS=0x3600000000000000000000000000000000000000
USDG_ADDRESS=
TREASURY_ALLOWED_RECIPIENTS=

# Arc routing is initially pinned to LI.FI. A second execution provider has not
# yet been verified, so provider fallback and route tournaments are fail-closed.
SWAP_PROVIDER=lifi
SWAP_FALLBACK_PROVIDER=
LI_FI_API_KEY=your_li_fi_api_key_here
LI_FI_INTEGRATOR=
USE_LI_FI=true
USE_UNISWAP_API=false
UNISWAP_API_KEY=
UNISWAP_PERMIT2_DISABLED=true
UNISWAP_RATE_LIMIT_RPS=4
UNISWAP_COOLDOWN_BASE_SECONDS=30
UNISWAP_COOLDOWN_MAX_SECONDS=900
UNISWAP_PROTOCOL_CACHE_TTL_SECONDS=300
UNISWAP_RATE_STATE_FILE=
SUSHI_API_KEY=
ZEROX_API_KEY=
ROUTE_TOURNAMENT_MODE=off
ROUTE_TOURNAMENT_CANARY=false
ROUTE_TOURNAMENT_PROVIDERS=lifi
ROUTE_TOURNAMENT_SETTLEMENTS=weth
ROUTE_TOURNAMENT_SHADOW_TIMEOUT_SECONDS=4
ROUTE_TOURNAMENT_GATE_TIMEOUT_SECONDS=12
ROUTE_TOURNAMENT_SPECULATIVE_FALLBACK_SECONDS=0

GRID_SPACING_PERCENT=6
MAX_POSITIONS=10
MAX_ACTIVE_POSITIONS=6
MIN_PROFIT_PERCENT=5
INITIAL_BUY_AMOUNT=5
SLIPPAGE_TOLERANCE=2
FAST_PROFIT=true
TRADEABLE_BALANCE_PERCENT=80
MOONBAG_PERCENTAGE=1

USE_GRIDLESS=true
GRIDLESS_BUY_THRESHOLD=-10
GRIDLESS_SELL_THRESHOLD=5
GRIDLESS_STOPLOSS_THRESHOLD=-25
GRIDLESS_STOPLOSS_ENABLED=false
GRIDLESS_LEADING_EDGE=true
GRIDLESS_BUY_COOLDOWN_SECONDS=0
GRIDLESS_BUY_EXECUTION_MARGIN=50

TAXED_TOKEN=false
TOKEN_TRANSFER_FEE_PERCENT=0
TAXED_TOKEN_SLIPPAGE_BUFFER_PERCENT=2
TAXED_TOKEN_FAILURE_COOLDOWN_SECONDS=300
AUTO_DETECT_TOKEN_TRANSFER_FEE=false
AUTO_DETECT_TOKEN_TRANSFER_FEE_MAX_PERCENT=13

# Arc has no wrapped-native leg. Trade through the 6-decimal USDC interface.
USE_ETH_TRADING=false
# Dollar amount kept untouched for gas. This is subtracted from the shared
# USDC balance even though trades use the ERC-20 interface.
ETH_GAS_RESERVE=1
TREASURY_POSITION_RESERVE_ETH=0
GAS_LIMIT_MULTIPLIER=1.10
GAS_PRICE_MULTIPLIER=1
GAS_PRICE_FRESHNESS_MULTIPLIER=1.01
# Values are USDC on Arc despite the legacy variable suffix.
MAX_SWAP_GAS_ETH=0.10
MAX_BUY_GAS_ETH=0.10
MAX_SELL_GAS_ETH=0.10
MAX_FEE_TRANSFER_GAS_ETH=0.05

BANK_PERCENTAGE=0
BANK_MIN_AMOUNT=1
PROFIT_FEE_PERCENT=0
PROFIT_FEE_WALLET=
MIN_PROFIT_FEE_TRANSFER_ETH=0.10

POLL_INTERVAL_SECONDS=20
STARTUP_JITTER_SECONDS=20
PERFORMANCE_TELEMETRY_EVERY_CYCLES=10
ANTI_MEV_JITTER=true
LOG_LEVEL=INFO
STATE_FILE=./data/positions_arc.json
COMPACT_MODE=false
MINIMAL_LOGS=false
MERCURY_EVOCATION=true
AUTO_RECONCILE_UNRESOLVED_BROADCAST=false
AUTO_RECONCILE_INTERVAL_SECONDS=30

DASHBOARD_URL=
DASHBOARD_API_KEY=
BOT_ID=
DASHBOARD_NAME=
DASHBOARD_GROUP=Arc
